server:
  port:  8081

spring:
  security:
    user:
      name: test
      password: test
  application:
    name:  jiajuxiaoshou
  datasource:
    druid:
      test-on-borrow: true
      test-while-idle:  true
    type:  com.alibaba.druid.pool.DruidDataSource
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://106.54.50.245:3306/home?setUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
    username:  root
    password:  root
  thymeleaf:
    cache:  false
    prefix: classpath:/templates/
    suffix: .html
    check-template-location: false

mybatis:
  type-aliases-package:  com.song.entity
  mapper-locations:  classpath:/mapper/*.xml


#cluster.datasource.url=jdbc:mysql://106.54.50.245:3306/home?useUnicode=true&characterEncoding=utf8
#cluster.datasource.username=root
#cluster.datasource.password=root
#cluster.datasource.driverClassName=com.mysql.jdbc.Driver